export const FETCH_USER = 'fetch_user'
export const CART_ADD_ITEM = 'cart_add_item'
export const CART_REMOVE_ITEM = 'cart_remove_item'
export const CART_SAVE_SHIPPING_ADDRESS = 'cart_save_shipping_address'
export const CART_SAVE_PAYMENT_METHOD = 'cart_save_payment_method'